netlify-templates/victor-hugo

README.md
Some quick edits to note the dependency on Hugo. Probably obvious, but it didn't occur to me to check for it first.
=> update readme to include note about Hugo dependency

gulpfile.babel.js
If hugo fails to build the site, we want to make sure gulp exits
with an appropriate error code so a netlify deploy fails
=> Make sure to exit with non-zero exit code on hugo error

README.md
The `app.js` file is being built to the site root, not a `js` subdirectory.  Update the README to reflect this.
=> Fix wrong directory for app.js in README

gulpfile.babel.js
**- Summary**
Fixes #22 
This change allows people to set custom imports in their main css file.
1. Create an imported css file and add it to the `main.css` file as described in #22.
2. Run `npm build`.
- Fixed issue that prevented people from importing css files into the `main.css` file.
=> Flip CSS tasks order to parse custom imports

package.json
**- Summary**
Included in Victor-Hugo's `package.json` are dependencies for `"autoprefixer": "^6.3.7"` and `"postcss-cssnext": "^2.7.0"`. However, [PostCSS CSSNext already has Autoprefixer baked in](http://cssnext.io/features/#automatic-vendor-prefixes), therefore seems it may be redundant to have the standalone. 
I tested and verified it is unnecessary with Gulp build first by installing and running Victor-Hugo `master` branch and adding `body { display: flex; }` in the `src/css/main.css` which then compiled to `body { display: -webkit-box; display: -ms-flexbox; display: flex; }`. 
I then removed the `node_modules/autoprefixer/` dir and ran `npm uninstall --save autoprefixer` to remove from `package.json` and replicated the same results were being output. 
**- Description …
=> remove autoprefixer duplicate dependency

package.json
**- Summary**
In Victor-Hugo's `package.json` there is a declared dependency for `postcss-loader`. However, it is not being used anywhere, therefore it seems unnecessary to have it declared.
I removed the `postcss-loader` dependency from `package.json` with `npm uninstall --save postcss-loader` and ran `npm start` to verify there were not breaking changes in UI and in console output.
remove unused postcss-loader as dependency
=> remove unused postcss-loader as dependency

gulpfile.babel.js
When there's a css error, the `npm run start` command exits. This forces the user to run the command again. With this change, I simply swallowed the error and output to stderr.
=> Prevent exiting on css error

gulpfile.babel.js
Reverts netlify/victor-hugo#32
@bryankang I've decided to revert this change. After thinking about it, people should not ignore those errors, otherwise they might end up with broken sites in production.
=> Revert "Prevent exiting on css error"

README.md, netlify.toml
So people start with a more modern version of Hugo when
they deploy their site on Netlify.
Signed-off-by: David Calavera <david.calavera@gmail.com>
**- Summary**
This ensures that Netlify uses a more modern version of Hugo when a site built with Victor-Hugo is deployed for the first time.
New users of Victor-Hugo might bump into issues right away because Netlify's default version of Hugo is older than their version. This will help with that problem.
Deploy a new site on Netlify.
Ensure that Netlify uses Hugo 0.21, the most recent version on May 30.
- Pin version of Hugo for Netlify's deploy to a more recent one.
=> Pin Hugo version on Netlify to the most recent one.

CONTRIBUTING.md, README.md, gulpfile.babel.js, netlify.toml, package.json
**- Summary**
Don't require hugo to be installed separately; instead add the node wrapper module [hugo-bin](https://www.npmjs.com/package/hugo-bin) as a npm dependency.
This PR simplifies the setup process and removes the need for users to go learn how to install hugo on their platform.
Instead they simply run `npm install` and hugo gets added to `node_modules/.bin`. In javascript we can pass `reauire('hugo-bin')` directly to `cp.spawn`.
---
hugo-bin ~~currently uses hugo [version 0.24.1](https://github.com/gohugoio/hugo/releases/tag/v0.24.1)~~, which can be updated via a simple change to the upstream `package.json` (see fenneclab/hugo-bin#23). _EDIT: Now uses latest version 0.25.1_
---
**- Test plan:** Existing tests should cover this change: if it is bad, hugo will completely fail.
**- …
=> Include hugo as a npm dependency

README.md, gulpfile.babel.js
**- Summary**
The environmental variables inside the gulp tasks make it easy to use them within theme files. It's now easy to have switch between environments where you might need another base-path (like for github pages) or maybe include a script for debugging.
You can query the environment variables within the theme with `getenv "NODE_ENV"` - it will return `development` for all hugo* tasks and `production` for all build* tasks.
I also fixed two linting errors, added some comments to the gulpfile and updated the Readme to include the latest additions.
I've added `{{ getenv "NODE_ENV" }}` to `site\layouts\index.html` and run `gulp hugo`, `gulp hugo-preview` and `gulp server` which all three would yield *development* in the resulting file. While `gulp build` and `gulp …
=> Environment variables

site/config.toml, site/layouts/index.html, site/layouts/partials/footer.html, site/layouts/partials/header.html, src/css/imports/reset.css, src/css/main.css, src/js/app.js
**- Summary**
For beginners and hopefully others, these changes should bring better default settings to the generated output of the first build. I disabled the RSS feed and the taxonomies to clean up the dist folder. The `title` and `baseURL` are now pulled from config and are added to the page's head. I also added a language parameter to the configuration and for output inside the head. Also changed and added some placeholder code in CSS and JS.
I have run `gulp server` and `npm run build` to review the changes. If you have had build the site before, you must empty the build beforehand since hugo does not clean the dist folder.
Nicer default values for config and theme
=> Some - hopefully - nicer defaults

package-lock.json, package.json
**- Summary**
Updated the hugo-bin version to match the newest hugo version and added the missing repository field to fix the npm warning.
Runned gulp server and npm install.
hugo-bin update / added repository field
=> Hugobin update & repository field

site/layouts/partials/header.html
**- Summary**
As reported by [jhabdas](https://github.com/netlify/victor-hugo/pull/40#pullrequestreview-67828718) I added the viewport extension to match newer iOS11 devices.
Sadly none. Don't have any iOS11 device.
Added viewport-fit=cover support for iOS11 devices with the new screens.
=> Extended viewport tag for iOS11

gulpfile.babel.js, package.json
Fixes #46 
**- Summary**
Currently you must stop the server/watcher and re-run to detect newly created files. This is cumbersome, and can be easily fixed by replacing the default `gulp.watch()` with the `gulp-watch` package (NPM).
```
npm install
npm run start
```
Terminal output before change == Terminal output after change
`gulp.watch()` replaced with `gulp-watch` to detect new files
=> Replace gulp.watch() with the gulp-watch package

gulpfile.babel.js, package.json
**- Summary**
The idea is to add a new Gulp task in order to move all the fonts form `src/fonts` folder to a new directory `dist/fonts`. The new folder will not have sub-folder.
**- Motivation**
1. Keep all 'static' files inside the folder `src`
2. Make easier to declare the `@fontface` without messing up with folders paths
1. Run`npm install`: gulp-flatten correctly installed
2. Run `npm start`: new fonts added or removed are moved into`src/fonts`
3. Run `npm run build`: all fonts are moved into `src/fonts`
New Gulp task to move all the fonts in a flattened directory inside dist.
=> New Gulp task to move all the fonts in a flattened directory inside dist

gulpfile.babel.js
**- Summary**
gulp.start() is never officially supported by gulp, it's better to use the functionality provided by gulp.watch(). 
See: gulpjs/gulp#755
Run `gulp server` to test.
Remove use gulp.start()
N/A
=> Remove use gulp.start()

site/layouts/partials/header.html
**- Summary**
The `<base>` tag is currently set to Hugo's `$.Site.BaseURL`. This is great for production builds, but doesn't work well with Netlify deploy previews — anchors/network requests on deploy previews still point to the production server, making it difficult to test changes.
Tested on an existing site build and fresh install.
This change checks for the `CONTEXT` env, then serves the `URL` or `DEPLOY_PRIME_URL` for production & previews, respectively - falling back to `$.Site.BaseURL`.
=> Check for Netlify deploy URLs in base tag

gulpfile.babel.js
**- Summary**
After an initial hugo-preview build, the runServer function reverts to running the non-preview hugo task.
(I've left the unused callback argument in place in case anyone else makes use of it in their local modifications. Also, the eslint rules as shipped do not complain.)
```
$ yarn start-preview
```
Wait for server start running.
```
^Z
$ bg
$ touch site/config.toml
```
Compare gulp output, before and after change.
server-preview: Ensure hugo-preview is run for subsequent builds, too.
I believe our cat is too deadly a creature to be appropriate, despite all its cuteness.
=> server-preview: Ensure hugo-preview is run for subsequent builds, too.

package.json, yarn.lock
`yarn run start` fails with node 11.1.0 (and most likely node 11.0.0 as well).
Upgrading `natives` in `package.json`'s `resolutions` block to version 1.1.6 solves this issue.
See: https://github.com/gulpjs/gulp/issues/2246
=> Fix `yarn run` with node version 11

site/layouts/_default/baseof.html
**- Summary**
Fixes a duplicate closing HTML tag.
Load the page and inspect the source to ensure the second head tag is gone.
- HTML markup cleanup
=> Remove duplicate closing tag for head

webpack.dev.js
fixes #167 
**- Summary**
Recent changes to the upstream clean-webpack-plugin have made the default path list no longer work. This pr changes the config structure to match the pattern
`npm run preview` and `npm start` now work previously they would error with 
```
Watching for config changes in $dir/go/src/github.com/kcollasarundell/victor-hugo/site/config.toml
$dir/go/src/github.com/kcollasarundell/victor-hugo/node_modules/clean-webpack-plugin/dist/clean-webpack-plugin.js:17
throw new Error(`clean-webpack-plugin only accepts an options object. See:
^
Error: clean-webpack-plugin only accepts an options object. See:
https://github.com/johnagan/clean-webpack-plugin#options-and-defaults-optional
at new CleanWebpackPlugin …
```
=> CleanWebpackPlugin has changed how it accepts configuration options

webpack.dev.js
**- Summary**
Fixes #174 by removing the `stats: "none"` setting from Webpack's devServer object to allow error logging. With the entire setting gone, the stats setting defaults to `normal` and maintains color in the terminal.
Generally just trigger an error somewhere in the SCSS or JS pipeline.
I created a `src/main.scss` file containing some syntax errors and imported it into `src/index.js`. This threw a specific, detailed error in the console for me, where in my instance I left off a closing bracket. If `stats: "none"` is added back, then the build silently fails without any error logging.
Added info and error logging to Webpack Dev Server.
=> Removed stats object from webpack devServer to allow default error logging

package.json
**- Summary**
Move the `--hot` flag from the `build:webpack` script to the `start:webpack` script and remove the `--inline` option.
It looks like the `--hot` and `--inline` flags, which I think are intended to be webpack-dev-server options, were mistakenly added to the `build:webpack` script and were adding unnecessary code to production JS bundles (see #178). The `--inline` flag can be removed altogether because the [webpack-dev-server default for `inline` is true](https://webpack.js.org/configuration/dev-server/#devserverinline). Closes #178.
Check browser console for webpack-dev-server messages displaying whether HMR is enabled or not.
Before this commit:
After this commit:
Enabled webpack hot module replacement (HMR) and fixed HMR …
=> Move HMR to dev task only

webpack.dev.js
Fix "TypeError: CleanWebpackPlugin is not a constructor" for clean-webpack-plugin >= 3.0.0
When using `npm run preview` with the latest version, an error is thrown as the CleanWebpackPlugin has changed in v. 3.0.0.
This change fixes the import.
=> Fix TypeError in CleanWebpackPlugin instantiation

.eslintrc.yml
ESLint seems to be reading the `parserOptions` config correctly (ES6 is currently linted correctly), but the extra `"` on `ecmaVersion` should be removed for clarity. Closes #176
**- Summary**
Remove extraneous quotation mark from .eslintrc.yml
Make sure ESLint continues to work properly with ES6 syntax. (It does.)
Remove extraneous quotation mark from .eslintrc.yml
=> Remove extraneous `"` from .eslintrc.yml
